Make production branch configurable in release functions
cloudogu/ces-build-lib pull request #57
Opened 2021-03-30 09:48 UTC by robertauer

Resolves #56

2021-03-31 18:46 UTC, schnatterer requested changes
I only reviewed the code - don't have an environment to test those changes at hand. I'm sure somebody else could do this more efficiently. Or maybe you can point me towards it.

Are there no tests involved?

2021-03-31 18:46 UTC, schnatterer commented on src/com/cloudogu/ces/cesbuildlib/GitFlow.groovy
> +        git.push("origin " + productionBranch + " develop ${releaseVersion}")
Why don't you use GString here - `origin ${productionBranch}..."`

2021-03-31 18:46 UTC, schnatterer commented on src/com/cloudogu/ces/cesbuildlib/GitFlow.groovy
> +    void finishRelease(String releaseVersion, String productionBranch="master") {
Formatting with spaces would make it easier to read IMO - `branch = "master"`

2021-03-31 18:46 UTC, schnatterer commented on src/com/cloudogu/ces/cesbuildlib/GitHub.groovy
> +    void createRelease(String releaseVersion, String changes, String productionBranch="master") {
Formatting with spaces would make it easier to read IMO - `branch = "master"`

2021-04-06 11:44 UTC, Subaro approved these changes

2021-04-06 14:27 UTC, merged